# Generated by Django 5.1.6 on 2025-09-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_purpose', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=50)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(max_length=20)),
                ('current_address', models.TextField()),
                ('employment_type', models.CharField(max_length=50)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('work_experience', models.IntegerField()),
                ('company_name', models.CharField(max_length=150)),
                ('existing_loans', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_age', models.CharField(max_length=50)),
                ('property_city', models.CharField(max_length=100)),
                ('property_area', models.IntegerField()),
                ('property_address', models.TextField()),
                ('agree_terms', models.BooleanField(default=False)),
                ('credit_check', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
