# Generated by Django 5.2.1 on 2025-08-27 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self-employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], max_length=20)),
                ('annual_income', models.CharField(choices=[('under-25k', 'Under ₹25,000'), ('25k-50k', '₹25,000 - ₹50,000'), ('50k-75k', '₹50,000 - ₹75,000'), ('75k-100k', '₹75,000 - ₹100,000'), ('over-100k', 'Over ₹100,000')], max_length=20)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='id_documents/')),
                ('security_question1', models.CharField(max_length=255)),
                ('security_question2', models.CharField(max_length=255)),
                ('initial_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_marketing', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='BankApp.profile')),
            ],
        ),
    ]
