# Generated by Django 5.2.1 on 2025-09-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0002_accountapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountapplication',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='accountapplication',
            old_name='agree_marketing',
            new_name='marketing_opt_in',
        ),
        migrations.RenameField(
            model_name='accountapplication',
            old_name='agree_terms',
            new_name='terms_accepted',
        ),
        migrations.RemoveField(
            model_name='accountapplication',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='accountapplication',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='accountapplication',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='accountapplication',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='accountapplication',
            name='security_question1',
        ),
        migrations.RemoveField(
            model_name='accountapplication',
            name='security_question2',
        ),
        migrations.RemoveField(
            model_name='accountapplication',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='birth_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='document_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='employment',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self-employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='income',
            field=models.CharField(blank=True, choices=[('under-25k', 'Under $25,000'), ('25k-50k', '$25,000 - $50,000'), ('50k-75k', '$50,000 - $75,000'), ('75k-100k', '$75,000 - $100,000'), ('over-100k', 'Over $100,000')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountapplication',
            name='account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountapplication',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountapplication',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountapplication',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='accountapplication',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
