# Generated by Django 4.2.16 on 2025-09-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BankApp", "0005_creditcardapplication_debitcardapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitcardapplication",
            name="account_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
