# Generated by Django 5.2.3 on 2025-09-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0003_rename_submitted_at_accountapplication_created_at_and_more'),
        ('BankApp', '0006_alter_debitcardapplication_account_number'),
    ]

    operations = [
    ]
